[tool.poetry]
name = "Iuvot"
version = "0.1.0"
description = ""
authors = ["Saptak S"]

[tool.poetry.dependencies]
python = "^3.9"
django = "^4.1"
pyotp = "^2.6.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
