# Generated by Django 4.1 on 2022-08-23 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expense_name", models.CharField(max_length=75)),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("IT", "IT related things"),
                            ("TR", "Travel"),
                            ("CS", "Cash expense"),
                            ("MS", "Miscellenous"),
                        ],
                        default="CS",
                        max_length=2,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "currency",
                    models.CharField(
                        choices=[
                            ("MTL", "MTL"),
                            ("MYR", "MYR"),
                            ("HUF", "HUF"),
                            ("BRL", "BRL"),
                            ("ZAR", "ZAR"),
                            ("USD", "USD"),
                            ("EUR", "EUR"),
                            ("THB", "THB"),
                            ("CHF", "CHF"),
                            ("TRY", "TRY"),
                            ("SKK", "SKK"),
                            ("LTL", "LTL"),
                            ("PHP", "PHP"),
                            ("GBP", "GBP"),
                            ("SIT", "SIT"),
                            ("CYP", "CYP"),
                            ("RUB", "RUB"),
                            ("TRL", "TRL"),
                            ("CZK", "CZK"),
                            ("ILS", "ILS"),
                            ("EEK", "EEK"),
                            ("SGD", "SGD"),
                            ("INR", "INR"),
                            ("NZD", "NZD"),
                            ("CAD", "CAD"),
                            ("LVL", "LVL"),
                            ("JPY", "JPY"),
                            ("PLN", "PLN"),
                            ("AUD", "AUD"),
                            ("MXN", "MXN"),
                            ("KRW", "KRW"),
                            ("HRK", "HRK"),
                            ("ISK", "ISK"),
                            ("BGN", "BGN"),
                            ("HKD", "HKD"),
                            ("NOK", "NOK"),
                            ("RON", "RON"),
                            ("CNY", "CNY"),
                            ("SEK", "SEK"),
                            ("ROL", "ROL"),
                            ("DKK", "DKK"),
                            ("IDR", "IDR"),
                        ],
                        default="INR",
                        max_length=3,
                    ),
                ),
                ("amount_in_inr", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_added", models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
